### ISSUE TITLE
Integration with Xcodegen

### ISSUE THREAD

**Issue by razor313** [mac-cain13/R.swift#846]
I want to integrate R.swift with [Xcodegen](https://github.com/yonaskolb/XcodeGen).
```
packages:
  RswiftGenerator:
    url: https://github.com/mac-cain13/R.swift
    from: 7.3.2
targets:
  MyApp:
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: RswiftGenerator
```
But it didn't work and it wasn't added to the `Run Build Tool Plug-ins` section.

![Screenshot 2023-09-04 at 18 35 02](https://github.com/mac-cain13/R.swift/assets/26047366/4ded8841-1aa5-479d-9211-acb51b1e3a75)

**_R.swift: 7.3.2_**
**_Xcodegen: 2.32.0
Xcode: 14.3_**

Is there any guideline or example where I can see how it could be?

**Comment by novr** [comment]
need dependencies?
```
targets:
  MyApp:
    dependencies:
      - package: Rswift
        product: RswiftLibrary
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: RswiftGenerator
```

**Comment by tomlokhorst** [comment]
I haven't used Xcodgen, so I don't know how this is supposed to work. 

One thing you could try is to update to Xcode 14.3.1, as Xcode 14.3 has an issue with SPM plugins.

**Comment by razor313** [comment]
> 

Added but it didn't work. :( 
My problem is, that the plug-in `RswiftGenerateInternalResources` is not being added to the project.

**Comment by takoikatakotako** [comment]
@razor313 
Hi!
XcodeGen 2.23.0 does not support BuildToolPlugin.
XcodeGen supports BuildToolPlugin since 2.37.0.

https://github.com/yonaskolb/XcodeGen/releases/tag/2.37.0

It worked like this.

```
packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift
    from: 7.4.0
```

```
targets:
  MyApp:
    dependencies:
      - package: Rswift
        product: RswiftLibrary
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
```

Xcode: 15.0.1
XcodeGen: 2.38.0
RSwift: R.Swift: 7.4.0
